/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Functioning */

#ifndef _Included_Functioning
#define _Included_Functioning
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef Functioning_TOP_ALIGNMENT
#define Functioning_TOP_ALIGNMENT 0.0f
#undef Functioning_CENTER_ALIGNMENT
#define Functioning_CENTER_ALIGNMENT 0.5f
#undef Functioning_BOTTOM_ALIGNMENT
#define Functioning_BOTTOM_ALIGNMENT 1.0f
#undef Functioning_LEFT_ALIGNMENT
#define Functioning_LEFT_ALIGNMENT 0.0f
#undef Functioning_RIGHT_ALIGNMENT
#define Functioning_RIGHT_ALIGNMENT 1.0f
#undef Functioning_serialVersionUID
#define Functioning_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
#undef Functioning_serialVersionUID
#define Functioning_serialVersionUID 4613797578919906343LL
/* Inaccessible static: dbg */
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: nameCounter */
#undef Functioning_serialVersionUID
#define Functioning_serialVersionUID -2728009084054400034LL
#undef Functioning_DIAMETER
#define Functioning_DIAMETER 20L
/*
 * Class:     Functioning
 * Method:    CFunctions
 * Signature: (CLjava/lang/String;Ljava/lang/String;Ljava/lang/String;C)V
 */
JNIEXPORT void JNICALL Java_Functioning_CFunctions
  (JNIEnv *, jobject, jchar, jstring, jstring, jstring, jchar);

#ifdef __cplusplus
}
#endif
#endif
